# "It took the night to believe"

language: c

compiler:
  - gcc
  - clang

before_install:
  - pip install codecov

before_script:
  - cmake .
  
sudo: false

addons:
  apt:
    packages:
    - cmake
    - libpopt-dev
    - doxygen

script:
    - make
    - make test
    - make doc

after_success:
  - codecov
