# "It took the night to believe"

# https://docs.travis-ci.com/user/trusty-ci-environment/
# Ubuntu Trusty is needed to get a sufficiently fresh CMake
# as of 2016-01-09 it's in beta.
sudo: required
dist: trusty

language: c

compiler:
  - gcc
  - clang

before_install:
  - pip install --user codecov

before_script:
  - cmake .
  
addons:
  apt:
    packages:
    - cmake
    - libpopt-dev
    - doxygen

script:
    - make
    - make test
    - make doc

after_success:
  - .local/bin/codecov
